FROM python:3.10-buster

# Install make
RUN apt-get update && apt-get install -y gcc python3-dev make

# Copy necessary files
COPY face_tally face_tally/
COPY Makefile Makefile
COPY requirements.txt requirements.txt
COPY setup.py setup.py

# Upgrade pip and install dependencies
RUN pip install --upgrade pip
RUN make install

# Additional commands
RUN make create_folders
CMD python face_tally/interface/main.py
